
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "Control-node"
  config.vm.network "private_network", ip: "192.168.1.2" 
  config.vm.synced_folder ".", "/vagrant", type: "nfs"
  config.vm.provision "shell", inline: "
  #/bin/sh
  sudo yum -y install epel-release
  echo 'inicio da instalação do ansible'
  sudo yum -y install ansible
  cat <<EOT >> /etc/hosts
  192.168.1.2 control-node
  192.168.1.3 app01
  192.168.1.4 db01
  EOT
  "
end
